default: ci

install:
    pnpm install

dev:
    pnpm dev

build:
    pnpm build

preview:
    pnpm preview

lint:
    pnpm biome lint .

format:
    pnpm biome format . --write

check:
    pnpm biome check .

typecheck:
    pnpm tsc -b

ci: check typecheck
